/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crudIncidencias;

import MenuInicio.InicioAdmin;
import conexion.conection;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;

import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author christian
 */
public class AddInsidencias extends javax.swing.JFrame {

    /**
     * Creates new form AddInsidencias
     */
    public AddInsidencias() {
        initComponents();
        Hora hilo = new Hora(horaSistema);
        hilo.start();
        this.setLocationRelativeTo(null);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        horaSistema = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbTipoInc = new javax.swing.JComboBox<>();
        jSeparator6 = new javax.swing.JSeparator();
        txtBuscar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        txtNombre = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        claveEmpl = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtObsInc = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        fechaIn = new com.toedter.calendar.JDateChooser();
        fechaFin = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Multiply_32px.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Expand_Arrow_32px.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/if_arrow_left2_1814084-2.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, -1, 40));

        horaSistema.setBackground(new java.awt.Color(255, 99, 71));
        horaSistema.setForeground(new java.awt.Color(255, 99, 71));
        horaSistema.setText("Hora del sistema");
        jPanel1.add(horaSistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 120, 20));

        jLabel4.setBackground(new java.awt.Color(255, 99, 71));
        jLabel4.setForeground(new java.awt.Color(255, 99, 71));
        jLabel4.setText("Tipo Incidencia");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 100, 20));

        cbTipoInc.setForeground(new java.awt.Color(255, 99, 71));
        cbTipoInc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo 1", "Tipo 2", "Tipo 3", "etc" }));
        jPanel1.add(cbTipoInc, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 220, 160, 30));

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 20, 170));

        txtBuscar.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        txtBuscar.setForeground(new java.awt.Color(204, 204, 204));
        txtBuscar.setText("insertar clave Empleado");
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 245, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Search_32px_2.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, 30));

        txtApellido.setBackground(new java.awt.Color(255, 99, 71));
        txtApellido.setForeground(new java.awt.Color(255, 99, 71));
        txtApellido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtApellido.setText("Apellido del empleado");
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 150, 20));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 150, 10));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 20, -1));

        txtNombre.setBackground(new java.awt.Color(255, 99, 71));
        txtNombre.setForeground(new java.awt.Color(255, 99, 71));
        txtNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNombre.setText("Nombre del empleado");
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 140, 20));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 160, 10));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 20, -1));

        claveEmpl.setBackground(new java.awt.Color(255, 99, 71));
        claveEmpl.setForeground(new java.awt.Color(255, 99, 71));
        claveEmpl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        claveEmpl.setText("Clave del empleado");
        jPanel1.add(claveEmpl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 130, 20));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 100, 10));

        txtObsInc.setForeground(new java.awt.Color(255, 99, 71));
        jPanel1.add(txtObsInc, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 470, 130));

        jLabel10.setBackground(new java.awt.Color(255, 99, 71));
        jLabel10.setForeground(new java.awt.Color(255, 99, 71));
        jLabel10.setText("Motivo de incidencia");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, -1, -1));

        jLabel11.setBackground(new java.awt.Color(255, 99, 71));
        jLabel11.setForeground(new java.awt.Color(255, 99, 71));
        jLabel11.setText("Dia Final:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, 70, 20));

        jButton1.setText("Enter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 560, 140, 40));

        btnBuscar.setText("buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, -1, 30));

        jLabel1.setBackground(new java.awt.Color(255, 99, 71));
        jLabel1.setForeground(new java.awt.Color(255, 99, 71));
        jLabel1.setText("Hora:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 40, 20));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 120, 10));

        fechaIn.setForeground(new java.awt.Color(255, 99, 71));
        jPanel1.add(fechaIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 290, 170, 30));

        fechaFin.setForeground(new java.awt.Color(255, 99, 71));
        jPanel1.add(fechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 340, 170, 30));

        jLabel12.setBackground(new java.awt.Color(255, 99, 71));
        jLabel12.setForeground(new java.awt.Color(255, 99, 71));
        jLabel12.setText("Dia Inicio:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, 70, 20));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 99, 71));
        jLabel2.setText("Agregar Incidencias");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 370, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 925, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        InicioAdmin in = new InicioAdmin();
        in.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel6MouseClicked
void mostrardatosBusqueda (String valor){
 String id = txtBuscar.getText();
         
     // int e = Integer.parseInt(txtEquipo.getText());
     if(!id.equals("")){
    try {
        
          {
          PreparedStatement ps = cn.prepareStatement("select * from empleado where clave='"+id+"'");
          ResultSet rs = ps.executeQuery();
          while(rs.next()){
              claveEmpl.setText(rs.getString(1));
              txtNombre.setText(rs.getString(2));
              txtApellido.setText(rs.getString(3));
              
              
             
           } 
          }
          
        } catch (SQLException e) {
        }
     }else{
         JOptionPane.showMessageDialog(rootPane,"debes buscar un empleado","Atencion", JOptionPane.WARNING_MESSAGE);
     }
    }
    
    
       // sql= "Select id,nombre,apellidos from empleados where nombre LIKE '%"+valor+"%'";

    
      
    
    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
       this.setState(AddInsidencias.ICONIFIED);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:  ^[x]

        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null,"¿Esta seguro que desea salir?", "Exit",dialog);

        if(result == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        // codigo
        
        
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
         String nombre = txtBuscar.getText();
        mostrardatosBusqueda(nombre);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      // Insertar datos BD  "dd-MM-yyyy"    "yyyy-MM-dd"
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy" );
        String fechaIni = sdf.format(fechaIn.getDate());
        String fechaFina = sdf.format(fechaFin.getDate());
        String tipo = (String) cbTipoInc.getSelectedItem();
        String observaciones = txtObsInc.getText();
        String claveEmp = claveEmpl.getText();

        try {

            if (tipo.isEmpty() || observaciones.isEmpty() || fechaIni.isEmpty()|| fechaFina.isEmpty()|| claveEmp.isEmpty()) {

                JOptionPane.showMessageDialog(null, "Es necesario rellenar todos los campos", "Atencion", JOptionPane.WARNING_MESSAGE);
            } else {
                PreparedStatement ps = cn.prepareStatement("INSERT INTO incidencias(tipo,Observaciones,fechaIni,fechaFin,claveEmp) VALUES (?,?,?,?,?)");
                ps.setString(1, tipo);
                ps.setString(2, observaciones);
                ps.setString(3, fechaIni);
                ps.setString(4, fechaFina);
                ps.setString(5, claveEmp);
                

                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Incidencia agregada ");
                

            }
        } catch (Exception ex) {
            System.out.println("Error en la inserción: " + ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddInsidencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddInsidencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddInsidencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddInsidencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddInsidencias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox<String> cbTipoInc;
    public javax.swing.JLabel claveEmpl;
    private com.toedter.calendar.JDateChooser fechaFin;
    private com.toedter.calendar.JDateChooser fechaIn;
    private javax.swing.JLabel horaSistema;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    public javax.swing.JLabel txtApellido;
    private javax.swing.JTextField txtBuscar;
    public javax.swing.JLabel txtNombre;
    private javax.swing.JTextField txtObsInc;
    // End of variables declaration//GEN-END:variables
conection cc = new conection();
    Connection cn = (Connection) cc.getConnection();
}
