/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crudIncidencias;

import CrudEmpleado.EliminarEmpleado;
import MenuInicio.InicioAdmin;
import conexion.conection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author christianlizarraga
 */
public class DeleteIncidencias extends javax.swing.JFrame {

    /**
     * Creates new form DeleteIncidencias
     */
    public DeleteIncidencias() {
        initComponents();
        mostrarDatos();
        Hora hilo = new Hora(horaSistema);
        hilo.start();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaInc = new javax.swing.JTable();
        horaSistema = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtClave = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtFechaIni = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtFechaFin = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtIdInc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 99, 71));
        jLabel1.setText("Eliminar Incidencias");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 390, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Search_32px_2.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, -1));

        txtBuscar.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        txtBuscar.setForeground(new java.awt.Color(255, 99, 71));
        txtBuscar.setText("insertar clave Empleado");
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 245, -1));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 150, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/if_arrow_left2_1814084-2.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, -1, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Expand_Arrow_32px.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 20, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Multiply_32px.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 20, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 99, 71));
        jLabel2.setForeground(new java.awt.Color(255, 99, 71));
        jLabel2.setText("Hora:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 70, -1));

        tablaInc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaInc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaIncMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaInc);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 660, -1));

        horaSistema.setBackground(new java.awt.Color(255, 99, 71));
        horaSistema.setForeground(new java.awt.Color(255, 99, 71));
        horaSistema.setText("jLabel3");
        jPanel1.add(horaSistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 90, -1));

        jLabel10.setBackground(new java.awt.Color(255, 99, 71));
        jLabel10.setForeground(new java.awt.Color(255, 99, 71));
        jLabel10.setText("Clave:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, 30));

        txtClave.setEditable(false);
        txtClave.setForeground(new java.awt.Color(255, 99, 71));
        txtClave.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 220, -1));

        jLabel11.setBackground(new java.awt.Color(255, 99, 71));
        jLabel11.setForeground(new java.awt.Color(255, 99, 71));
        jLabel11.setText("Nombre:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        txtNombre.setEditable(false);
        txtNombre.setForeground(new java.awt.Color(255, 99, 71));
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 220, -1));

        jLabel12.setBackground(new java.awt.Color(255, 99, 71));
        jLabel12.setForeground(new java.awt.Color(255, 99, 71));
        jLabel12.setText("Apellido:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        txtApellido.setEditable(false);
        txtApellido.setForeground(new java.awt.Color(255, 99, 71));
        txtApellido.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 220, -1));

        jLabel13.setBackground(new java.awt.Color(255, 99, 71));
        jLabel13.setForeground(new java.awt.Color(255, 99, 71));
        jLabel13.setText("Tipo");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        txtTipo.setEditable(false);
        txtTipo.setForeground(new java.awt.Color(255, 99, 71));
        txtTipo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(txtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 220, -1));

        jLabel14.setBackground(new java.awt.Color(255, 99, 71));
        jLabel14.setForeground(new java.awt.Color(255, 99, 71));
        jLabel14.setText("Fecha Inicio");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, -1, -1));

        txtFechaIni.setEditable(false);
        txtFechaIni.setForeground(new java.awt.Color(255, 99, 71));
        txtFechaIni.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(txtFechaIni, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 220, -1));

        jLabel15.setBackground(new java.awt.Color(255, 99, 71));
        jLabel15.setForeground(new java.awt.Color(255, 99, 71));
        jLabel15.setText("Fecha Fin");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, -1, -1));

        txtFechaFin.setEditable(false);
        txtFechaFin.setForeground(new java.awt.Color(255, 99, 71));
        txtFechaFin.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(txtFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 220, -1));

        jButton1.setText("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 100, 170, 50));

        txtIdInc.setBackground(new java.awt.Color(255, 255, 255));
        txtIdInc.setForeground(new java.awt.Color(255, 255, 255));
        txtIdInc.setText("w");
        jPanel1.add(txtIdInc, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 957, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        // codigo
        String Nombre = txtBuscar.getText();
        mostrardatosBusqueda(Nombre);
    }//GEN-LAST:event_txtBuscarKeyReleased
void mostrardatosBusqueda (String valor){
    String []datos = new String [9];
    DefaultTableModel modelo = new DefaultTableModel();
     modelo.addColumn("Clave");
    modelo.addColumn("Nombre");
    modelo.addColumn("Apellido");
    modelo.addColumn("Tipo");
    modelo.addColumn("Observaciones");
    modelo.addColumn("Fecha Inicio");
    modelo.addColumn("Fecha Final");
    modelo.addColumn("Folio");
  
    tablaInc.setModel(modelo);
    String sql;
    String sqlap;

        //sql= "Select clave,nombre,apellido,email,RFC,claveP,departamento from empleado where nombre LIKE '%"+valor+"%'";
    sql= "Select clave,nombre,apellido,tipo, observaciones, fechaIni,fechaFin,idIncidencia from empleado join incidencias on \n" +
"empleado.clave=incidencias.claveEmp where nombre LIKE '%"+valor+"%'";

    try {
        PreparedStatement ps = cn.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();
        while(rs.next()){
        datos[0]=rs.getString(1);
        datos[1]=rs.getString(2);
        datos[2]=rs.getString(3);
        datos[3]=rs.getString(4);
        datos[4]=rs.getString(5);
        datos[5]=rs.getString(6);
        datos[6]=rs.getString(7);
        datos[7]=rs.getString(8);
       
        modelo.addRow(datos);
        }
   }
    catch (SQLException e) {
        System.out.println(e);
    }

    
      
    }
    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        InicioAdmin in = new InicioAdmin();
        in.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel6MouseClicked
public void mostrarDatos(){
      String []datos = new String [11];
    DefaultTableModel modelo = new DefaultTableModel();
    modelo.addColumn("Clave");
    modelo.addColumn("Nombre");
    modelo.addColumn("Apellido");
    modelo.addColumn("Tipo");
    modelo.addColumn("Observaciones");
    modelo.addColumn("Fecha Inicio");
    modelo.addColumn("Fecha Final");
    modelo.addColumn("Folio");
 
    
tablaInc.setModel(modelo);
   try {
        PreparedStatement ps = cn.prepareStatement("Select clave,nombre,apellido,tipo, observaciones, fechaIni,fechaFin,idIncidencia from empleado join incidencias on \n" +
"empleado.clave=incidencias.claveEmp;");
        ResultSet rs = ps.executeQuery();
        while(rs.next()){
        datos[0]=rs.getString(1);
        datos[1]=rs.getString(2);
        datos[2]=rs.getString(3);
        datos[3]=rs.getString(4);
        datos[4]=rs.getString(5);
        datos[5]=rs.getString(6);
        datos[6]=rs.getString(7);
        datos[7]=rs.getString(8);
        
       
        modelo.addRow(datos);
        }
   }
    catch (Exception e) {
    }
}
    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        this.setState(AddInsidencias.ICONIFIED);
    }//GEN-LAST:event_jLabel7MouseClicked
public void LimpiarCajas(){
    txtApellido.setText(null);
    txtClave.setText(null);
    txtFechaFin.setText(null);
    txtFechaIni.setText(null);
    txtNombre.setText(null);
    txtTipo.setText(null);
           
}

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:  ^[x]

        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null,"¿Esta seguro que desea salir?", "Exit",dialog);

        if(result == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void tablaIncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaIncMouseClicked
        // TODO add your handling code here:
        int i = tablaInc.getSelectedRow();
      TableModel model = tablaInc.getModel();
      
      txtClave.setText(model.getValueAt(i,0).toString());
      
      txtNombre.setText(model.getValueAt(i,1).toString());

        txtApellido.setText(model.getValueAt(i,2).toString());

        txtTipo.setText(model.getValueAt(i,3).toString());
        
        txtFechaIni.setText(model.getValueAt(i,5).toString());
        
        txtFechaFin.setText(model.getValueAt(i,6).toString());
        txtIdInc.setText(model.getValueAt(i,7).toString());
    }//GEN-LAST:event_tablaIncMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            //boton borrar
            // String query = "DELETE FROM empleado WHERE nombre = "+txtNombre.getText();
            String id=txtIdInc.getText();
            String query ="DELETE FROM incidencias WHERE idIncidencia='"+id+"'";
            Statement sent=cn.createStatement();
            int s=sent.executeUpdate(query);
            
            if (s>0){
            JOptionPane.showMessageDialog(null, "Datos eliminados");
            mostrarDatos();
            LimpiarCajas();
            }
        } catch (SQLException ex) {
            Logger.getLogger(EliminarEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteIncidencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteIncidencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteIncidencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteIncidencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteIncidencias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel horaSistema;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tablaInc;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtFechaFin;
    private javax.swing.JTextField txtFechaIni;
    private javax.swing.JLabel txtIdInc;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
conection cc = new conection();
    Connection cn = (Connection) cc.getConnection();
}
