/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crudIncidencias;

import MenuInicio.InicioAdmin;
import conexion.conection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author christianlizarraga
 */
public class EditarInc extends javax.swing.JFrame {

    /**
     * Creates new form EditarInc
     */
    public EditarInc() {
        initComponents();
        mostrarDatos();
         Hora hilo = new Hora(horaSistema);
        hilo.start();
        this.setLocationRelativeTo(null);
//        Calendar c2 = new GregorianCalendar();
//        jcFechaIn.setCalendar(c2);
//        jcFehaDFin.setCalendar(c2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        txtBuscar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        horaSistema = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaInc = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtIdInc = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtObs = new javax.swing.JTextArea();
        cbTipo = new javax.swing.JComboBox<>();
        fechaIni = new com.toedter.calendar.JDateChooser();
        fechaFin = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 99, 71));
        jLabel1.setText("Editar Incidencias");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 330, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/if_arrow_left2_1814084-2.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, -1, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Expand_Arrow_32px.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 20, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Multiply_32px.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 20, -1, -1));

        jDateChooser1.setForeground(new java.awt.Color(255, 99, 71));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 150, 30));

        txtBuscar.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        txtBuscar.setForeground(new java.awt.Color(255, 99, 71));
        txtBuscar.setText("insertar clave Empleado");
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 245, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Search_32px_2.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, -1));

        horaSistema.setBackground(new java.awt.Color(255, 99, 71));
        horaSistema.setForeground(new java.awt.Color(255, 99, 71));
        horaSistema.setText("jLabel3");
        jPanel1.add(horaSistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 90, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 70, -1));

        jLabel2.setBackground(new java.awt.Color(255, 99, 71));
        jLabel2.setForeground(new java.awt.Color(255, 99, 71));
        jLabel2.setText("Hora:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jButton1.setText("Editar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 100, -1, -1));

        tablaInc.setForeground(new java.awt.Color(255, 99, 71));
        tablaInc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaInc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaIncMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaInc);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 700, -1));

        jLabel14.setBackground(new java.awt.Color(255, 99, 71));
        jLabel14.setForeground(new java.awt.Color(255, 99, 71));
        jLabel14.setText("Fecha Inicio");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        jLabel15.setBackground(new java.awt.Color(255, 99, 71));
        jLabel15.setForeground(new java.awt.Color(255, 99, 71));
        jLabel15.setText("Fecha Fin");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, -1, -1));

        txtIdInc.setText("jLabel3");
        jPanel1.add(txtIdInc, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel16.setBackground(new java.awt.Color(255, 99, 71));
        jLabel16.setForeground(new java.awt.Color(255, 99, 71));
        jLabel16.setText("Tipo");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel17.setBackground(new java.awt.Color(255, 99, 71));
        jLabel17.setForeground(new java.awt.Color(255, 99, 71));
        jLabel17.setText("Observaciones:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        txtObs.setColumns(20);
        txtObs.setForeground(new java.awt.Color(255, 99, 71));
        txtObs.setRows(5);
        jScrollPane2.setViewportView(txtObs);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 240, 110));

        cbTipo.setForeground(new java.awt.Color(255, 99, 71));
        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo 1", "Tipo 2", "Tipo 3", "etc" }));
        jPanel1.add(cbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 150, 30));

        fechaIni.setForeground(new java.awt.Color(255, 99, 71));
        jPanel1.add(fechaIni, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 180, -1));

        fechaFin.setForeground(new java.awt.Color(255, 99, 71));
        jPanel1.add(fechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 180, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        InicioAdmin in = new InicioAdmin();
        in.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        this.setState(AddInsidencias.ICONIFIED);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:  ^[x]

        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null,"¿Esta seguro que desea salir?", "Exit",dialog);

        if(result == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel9MouseClicked
public void mostrarDatos(){
      String []datos = new String [11];
    DefaultTableModel modelo = new DefaultTableModel();
    modelo.addColumn("Clave");
    modelo.addColumn("Nombre");
    modelo.addColumn("Apellido");
    modelo.addColumn("Tipo");
    modelo.addColumn("Observaciones");
    modelo.addColumn("Fecha Inicio");
    modelo.addColumn("Fecha Final");
    modelo.addColumn("Folio");
 
    
tablaInc.setModel(modelo);
   try {
        PreparedStatement ps = cn.prepareStatement("Select clave,nombre,apellido,tipo, observaciones, fechaIni,fechaFin,idIncidencia from empleado join incidencias on \n" +
"empleado.clave=incidencias.claveEmp;");
        ResultSet rs = ps.executeQuery();
        while(rs.next()){
        datos[0]=rs.getString(1);
        datos[1]=rs.getString(2);
        datos[2]=rs.getString(3);
        datos[3]=rs.getString(4);
        datos[4]=rs.getString(5);
        datos[5]=rs.getString(6);
        datos[6]=rs.getString(7);
        datos[7]=rs.getString(8);
        
       
        modelo.addRow(datos);
        }
   }
    catch (Exception e) {
    }
}
   
    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        // codigo
        String Nombre = txtBuscar.getText();
        mostrardatosBusqueda(Nombre);
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         //TODO add your handling code here:
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy" );
        String clave = txtIdInc.getText();
   String tipo = (String) cbTipo.getSelectedItem();
   String observaciones = txtObs.getText();
   String fechIni = sdf.format(fechaIni.getDate());
        String fechaFina = sdf.format(fechaFin.getDate());
   
    if(!clave.equals("") & !observaciones.equals("")){
    try {   
       int res= JOptionPane.showConfirmDialog(rootPane,"estas seguro que deseas actualizar los datos");
        if(res==0){
        PreparedStatement ps=cn.prepareStatement("UPDATE incidencias SET tipo='"+tipo+"',Observaciones='"+observaciones+"',fechaIni='"+fechIni+"',fechaFin='"+fechaFina+"' where idIncidencia= '"+clave+"'");
            ps.executeUpdate();
            
           
              JOptionPane.showMessageDialog(null, "Datos Actualizados");  
         //  LimpiarCajas();
         //  Enabletxt();
            
        }else{
            JOptionPane.showMessageDialog(rootPane, "no se guardaron los cambios","Atencion", JOptionPane.WARNING_MESSAGE);
            
           // Enabletxt();
           // LimpiarCajas();
            //txtBuscar.setEnabled(true);
        }
               
    } 
    catch (Exception e) {
    }
    }else{
        JOptionPane.showMessageDialog(rootPane, "debes llenar todas las cajas de texto","Atencion", JOptionPane.WARNING_MESSAGE);
       
    }
        
       
    
    }//GEN-LAST:event_jButton1ActionPerformed

    void mostrardatosBusqueda (String valor){
    String []datos = new String [9];
    DefaultTableModel modelo = new DefaultTableModel();
     modelo.addColumn("Clave");
    modelo.addColumn("Nombre");
    modelo.addColumn("Apellido");
    modelo.addColumn("Tipo");
    modelo.addColumn("Observaciones");
    modelo.addColumn("Fecha Inicio");
    modelo.addColumn("Fecha Final");
    modelo.addColumn("Folio");
  
    tablaInc.setModel(modelo);
    String sql;
    String sqlap;

        //sql= "Select clave,nombre,apellido,email,RFC,claveP,departamento from empleado where nombre LIKE '%"+valor+"%'";
    sql= "Select clave,nombre,apellido,tipo, observaciones, fechaIni,fechaFin,idIncidencia from empleado join incidencias on \n" +
"empleado.clave=incidencias.claveEmp where nombre LIKE '%"+valor+"%'";

    try {
        PreparedStatement ps = cn.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();
        while(rs.next()){
        datos[0]=rs.getString(1);
        datos[1]=rs.getString(2);
        datos[2]=rs.getString(3);
        datos[3]=rs.getString(4);
        datos[4]=rs.getString(5);
        datos[5]=rs.getString(6);
        datos[6]=rs.getString(7);
        datos[7]=rs.getString(8);
       
        modelo.addRow(datos);
        }
   }
    catch (SQLException e) {
        System.out.println(e);
    }

    
      
    }
    private void tablaIncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaIncMouseClicked
        // TODO add your handling code here:
        
        int i = tablaInc.getSelectedRow();
        TableModel model = tablaInc.getModel();
       
        cbTipo.setSelectedItem(model.getValueAt(i,3).toString());

        txtObs.setText(model.getValueAt(i,4).toString());
//
//        fechaIni.setDateFormatString(model.getValueAt(i,5).toString());
//
//       fechaFin.setDateFormatString((String) model.getValueAt(i,6));
           txtIdInc.setText(model.getValueAt(i,7).toString());
    }//GEN-LAST:event_tablaIncMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarInc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarInc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarInc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarInc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarInc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbTipo;
    private com.toedter.calendar.JDateChooser fechaFin;
    private com.toedter.calendar.JDateChooser fechaIni;
    private javax.swing.JLabel horaSistema;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tablaInc;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JLabel txtIdInc;
    private javax.swing.JTextArea txtObs;
    // End of variables declaration//GEN-END:variables
conection cc = new conection();
    Connection cn = (Connection) cc.getConnection();
}
