/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CrudEmpleado;

import MenuInicio.InicioAdmin;
import conexion.conection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author christian
 */
public class EditarEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form EditarEmpleado
     */
    public EditarEmpleado() {
        initComponents();
        Enabletxt();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtAceptar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        cbDepartamento = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtRfc = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtClavep = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 99, 71));
        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 99, 71));
        jLabel1.setText("Editar Empleado");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 200, -1));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 157, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 99, 71));
        jLabel3.setForeground(new java.awt.Color(255, 99, 71));
        jLabel3.setText("Buscar Clave:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        txtBuscar.setForeground(new java.awt.Color(255, 99, 71));
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 192, 25));

        jLabel4.setBackground(new java.awt.Color(255, 99, 71));
        jLabel4.setForeground(new java.awt.Color(255, 99, 71));
        jLabel4.setText("Nombre:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        txtNombre.setForeground(new java.awt.Color(255, 99, 71));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 131, -1));

        jLabel5.setBackground(new java.awt.Color(255, 99, 71));
        jLabel5.setForeground(new java.awt.Color(255, 99, 71));
        jLabel5.setText("Apellidos:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, -1));

        txtApellido.setForeground(new java.awt.Color(255, 99, 71));
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 131, -1));

        jLabel6.setBackground(new java.awt.Color(255, 99, 71));
        jLabel6.setForeground(new java.awt.Color(255, 99, 71));
        jLabel6.setText("Departamento:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, -1, -1));

        txtAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Enter_OFF.png"))); // NOI18N
        txtAceptar.setBorderPainted(false);
        txtAceptar.setContentAreaFilled(false);
        txtAceptar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Enter_ON.png"))); // NOI18N
        txtAceptar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Enter_ON.png"))); // NOI18N
        txtAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(txtAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 580, 115, 37));

        jButton2.setText("Nuevo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 580, 112, 41));

        jButton3.setText("Buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 117, 41));

        cbDepartamento.setForeground(new java.awt.Color(255, 99, 71));
        cbDepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrativo", "Directivo", "Docente" }));
        jPanel1.add(cbDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 350, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Multiply_32px.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Expand_Arrow_32px.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/if_arrow_left2_1814084-2.png"))); // NOI18N
        jLabel9.setToolTipText("");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, 50, 40));

        jLabel10.setBackground(new java.awt.Color(255, 99, 71));
        jLabel10.setForeground(new java.awt.Color(255, 99, 71));
        jLabel10.setText("Email");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, -1, -1));

        txtEmail.setForeground(new java.awt.Color(255, 99, 71));
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 131, -1));

        jLabel11.setBackground(new java.awt.Color(255, 99, 71));
        jLabel11.setForeground(new java.awt.Color(255, 99, 71));
        jLabel11.setText("RFC:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        txtRfc.setForeground(new java.awt.Color(255, 99, 71));
        jPanel1.add(txtRfc, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 150, -1));

        jLabel12.setBackground(new java.awt.Color(255, 99, 71));
        jLabel12.setForeground(new java.awt.Color(255, 99, 71));
        jLabel12.setText("Clave Presupuestal:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, -1, -1));

        txtClavep.setForeground(new java.awt.Color(255, 99, 71));
        jPanel1.add(txtClavep, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 160, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        txtBuscar.setEnabled(true);
        LimpiarCajas();
        Enabletxt();
        
        
    }//GEN-LAST:event_jButton2ActionPerformed
public void LimpiarCajas(){
    
    txtApellido.setText(null);
    txtBuscar.setText(null);
    txtEmail.setText(null);
    txtRfc.setText(null);
    txtClavep.setText(null);
   // txtDepartamento.setText(null);
    
    txtNombre.setText(null);
}
public void Enabletxt(){
    txtNombre.setEnabled(false);
        txtApellido.setEnabled(false);
        cbDepartamento.setEnabled(false);
        txtClavep.setEnabled(false);
        txtEmail.setEnabled(false);
        txtRfc.setEnabled(false);
        
}
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         String id = txtBuscar.getText();
         
     // int e = Integer.parseInt(txtEquipo.getText());
     if(!id.equals("")){
    try {
        
          {
          PreparedStatement ps = cn.prepareStatement("select * from empleado where clave='"+id+"'");
          ResultSet rs = ps.executeQuery();
          while(rs.next()){
              txtNombre.setText(rs.getString(2));
              txtApellido.setText(rs.getString(3));
              txtEmail.setText(rs.getString(4));
              txtRfc.setText(rs.getString(5));
              txtClavep.setText(rs.getString(6));
              cbDepartamento.setSelectedItem(rs.getString(7));
              
             txtBuscar.setEnabled(false);
             txtNombre.setEnabled(true);
        txtApellido.setEnabled(true);
        txtEmail.setEnabled(true);
        txtRfc.setEnabled(true);
        txtClavep.setEnabled(true);
        cbDepartamento.setEnabled(true);
        txtAceptar.setEnabled(true);
           } 
          }
          
        } catch (SQLException e) {
        }
     }else{
         JOptionPane.showMessageDialog(rootPane,"debes buscar un empleado","Atencion", JOptionPane.WARNING_MESSAGE);
     }
    }//GEN-LAST:event_jButton3ActionPerformed
public void editardatos(){
    
    String id = txtBuscar.getText();
    String nombre =txtNombre.getText();
    String apellido=txtApellido.getText();
    String email=txtEmail.getText();
    String rfc=txtRfc.getText();
    String claveP=txtClavep.getText();
   // String departamento=txtDepartamento.getText();
    String departamento =(String)cbDepartamento.getSelectedItem();
    if(!nombre.equals("") & !apellido.equals("")){
    try {   
       int res= JOptionPane.showConfirmDialog(rootPane,"estas seguro que deseas actualizar los datos");
        if(res==0){
        PreparedStatement ps=cn.prepareStatement("UPDATE empleado SET nombre='"+nombre+"',apellido='"+apellido+"',email='"+email+"',RFC='"+rfc+"',claveP='"+claveP+"',departamento='"+departamento+"' WHERE clave='"+id+"'");
            ps.executeUpdate();
            
           
              JOptionPane.showMessageDialog(null, "Datos Actualizados");  
           LimpiarCajas();
           Enabletxt();
            
        }else{
            JOptionPane.showMessageDialog(rootPane, "no se guardaron los cambios","Atencion", JOptionPane.WARNING_MESSAGE);
            
            Enabletxt();
            LimpiarCajas();
            txtBuscar.setEnabled(true);
        }
               
    } 
    catch (Exception e) {
    }
    }else{
        JOptionPane.showMessageDialog(rootPane, "debes llenar todas las cajas de texto","Atencion", JOptionPane.WARNING_MESSAGE);
       
    }
     
}
    private void txtAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAceptarActionPerformed
       // TODO add your handling code here:
     String id= txtBuscar.getText();
         if(!id.equals("")){
        editardatos();
       
        txtBuscar.setEnabled(true);
         }else{
             JOptionPane.showMessageDialog(rootPane, "debes llenar todas las cajas","Atencion", JOptionPane.WARNING_MESSAGE);
             
         }
        
    }//GEN-LAST:event_txtAceptarActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
         int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null,"¿Esta seguro que desea salir?", "Exit",dialog);

        if(result == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
         this.setState(EditarEmpleado.ICONIFIED);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        InicioAdmin in = new InicioAdmin();
      in.setVisible(true);
      dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbDepartamento;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton txtAceptar;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtClavep;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRfc;
    // End of variables declaration//GEN-END:variables
conection cc = new conection();
Connection cn = (Connection) cc.getConnection();
}
