/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MenuInicio;

import AppPackage.AnimationClass;

import CrudEmpleado.AgregarEmpleado;
import CrudEmpleado.BuscarEmpleado;
import CrudEmpleado.EditarEmpleado;
import CrudEmpleado.EliminarEmpleado;
import LogIn.LogIn;
import static LogIn.LogIn.txtUser;
import Modelo.ModeloExcel;
import conexion.conection;
import crudIncidencias.AddInsidencias;
import crudIncidencias.ConsInc;
import crudIncidencias.DeleteIncidencias;
import crudIncidencias.EditarInc;
import java.awt.List;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import xls.xlsFrame;

/**
 *
 * @author christian
 */
public class InicioAdmin extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public InicioAdmin() {
        initComponents();
       
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jlAgregar = new javax.swing.JLabel();
        jlEliminar = new javax.swing.JLabel();
        jlEditar = new javax.swing.JLabel();
        jlBuscar = new javax.swing.JLabel();
        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        lb4 = new javax.swing.JLabel();
        lbmenu = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Buscar Incidencias");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 140, 160, 50));

        jButton2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jButton2.setText("Editar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 300, 170, 70));
        jButton2.getAccessibleContext().setAccessibleName("\nEditar");

        jButton3.setText("adjuntar xls");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 450, 170, 60));

        jButton4.setText("Imprimir Reporte");
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 530, 190, 50));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/if_Continue_ellipsis_menu_more_options_1886823-2.png"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jlAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/if_Collaboration_group_people_men_user_team_users_1886784.png"))); // NOI18N
        jlAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlAgregarMouseClicked(evt);
            }
        });
        jPanel1.add(jlAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 120, -1, -1));

        jlEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/if_Delete_dustbin_empty_recycle_recycling_remove_trash_1886812.png"))); // NOI18N
        jlEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlEliminarMouseClicked(evt);
            }
        });
        jPanel1.add(jlEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 350, -1, -1));

        jlEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/if_Clipboard_tasks_report_business_checking_verification_list_1886797-2.png"))); // NOI18N
        jlEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlEditarMouseClicked(evt);
            }
        });
        jPanel1.add(jlEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 230, -1, -1));

        jlBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/if_search-user_46833.png"))); // NOI18N
        jlBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlBuscarMouseClicked(evt);
            }
        });
        jPanel1.add(jlBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 480, -1, -1));

        lb1.setBackground(new java.awt.Color(238, 112, 82));
        lb1.setForeground(new java.awt.Color(238, 112, 82));
        lb1.setText("Buscar");
        jPanel1.add(lb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 560, -1, -1));

        lb2.setBackground(new java.awt.Color(238, 112, 82));
        lb2.setForeground(new java.awt.Color(238, 112, 82));
        lb2.setText("Eliminar");
        jPanel1.add(lb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 440, -1, -1));

        lb3.setBackground(new java.awt.Color(238, 112, 82));
        lb3.setForeground(new java.awt.Color(238, 112, 82));
        lb3.setText("Editar");
        jPanel1.add(lb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 310, -1, -1));

        lb4.setBackground(new java.awt.Color(238, 112, 82));
        lb4.setForeground(new java.awt.Color(238, 112, 82));
        lb4.setText("Agregar");
        jPanel1.add(lb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 200, -1, -1));

        lbmenu.setBackground(new java.awt.Color(238, 112, 82));
        lbmenu.setForeground(new java.awt.Color(238, 112, 82));
        lbmenu.setText("Menu Empleados");
        jPanel1.add(lbmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/if_arrow_left2_1814084-2.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 18, -1, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Multiply_32px.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Expand_Arrow_32px.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, -1, -1));

        jButton5.setText("Añadir Incidencias");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, 170, 60));

        jButton6.setText("Eliminar Incidencias");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 390, 170, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lfogo 2.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 400, 430));

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Lucida Grande", 0, 42)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(168, 0, 0));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Cecati 23");
        jTextField1.setBorder(null);
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 210, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    xls.xlsFrame xls = new xlsFrame();
    
    xls.setVisible(true);
        dispose();
               
        
    }//GEN-LAST:event_jButton3ActionPerformed
public void inisesion(){
   ArrayList<String> resiltados = new ArrayList<String>();
    
          String user= txtUser.getText();
       //   txtNombresesion.setText(user);
    try {
        PreparedStatement ps = cn.prepareStatement("SELECT nombre,apellido FROM "
                + "empleado join usuario on empleado.clave=usuario.claveEmp where usuario='"+user+"'");
        ResultSet rs = ps.executeQuery();
        
        while(rs.next()){
     String resultado= rs.getString(1);
     String resultado2= rs.getString(2);
           // System.out.println(resultado);
            resiltados.add(resultado);
            resiltados.add(resultado2);
        }
        
    } catch (Exception e) {
        System.out.println(e);
    }
    
     System.out.println(resiltados.get(0));
   System.out.println(resiltados.get(1));
}
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // evento menu
        
        AnimationClass agregar = new AnimationClass();
        
        agregar.jLabelXRight(-80, 40, 10, 5, jlAgregar);
        
        ///labels
         AnimationClass lb1 = new AnimationClass();           ////Buscar
         lb1.jLabelXRight(-80, 50, 10, 5, this.lb1);
         AnimationClass lb2 = new AnimationClass();           ////Eliminar
         lb2.jLabelXRight(-80, 50, 10, 5, this.lb2);          
         AnimationClass lb3 = new AnimationClass();           ////Editar
         lb3.jLabelXRight(-80, 55, 10, 5, this.lb3);
         AnimationClass lb4 = new AnimationClass();           ////Agregar
         lb4.jLabelXRight(-80, 50, 10, 5, this.lb4);
        
         AnimationClass editar = new AnimationClass();
        
        editar.jLabelXRight(-80, 40, 10, 5, jlEditar);
        
         AnimationClass eliminar = new AnimationClass();
        
        eliminar.jLabelXRight(-80, 40, 10, 5, jlEliminar);
        
        AnimationClass buscar = new AnimationClass();
        
        buscar.jLabelXRight(-80, 40, 10, 5, jlBuscar);
        
        //<------------------------------------------------
        AnimationClass agregarr = new AnimationClass();
      
        agregarr.jLabelXLeft(40, -80, 10, 5, jlAgregar);
        
        ///labels
        
        AnimationClass lbb1 = new AnimationClass();
         lbb1.jLabelXLeft(50, -80, 10, 5, this.lb1);    ////Buscar
          AnimationClass lbb2 = new AnimationClass();
         lbb2.jLabelXLeft(50, -80, 10, 5, this.lb2);     ///Eliminar
          AnimationClass lbb3 = new AnimationClass();
         lbb3.jLabelXLeft(55, -80, 10, 5, this.lb3);       ///Editar
          AnimationClass lbb4 = new AnimationClass();
         lbb4.jLabelXLeft(50, -80, 10, 5, this.lb4);     ///Agregar
        
         AnimationClass editarr = new AnimationClass();
        
        editarr.jLabelXLeft(40, -80, 10, 5, jlEditar);
        
         AnimationClass eliminarr = new AnimationClass();
        
        eliminarr.jLabelXLeft(40, -80, 10, 5, jlEliminar);
        
        AnimationClass buscarr = new AnimationClass();
        
        buscarr.jLabelXLeft(40, -80, 10, 5, jlBuscar);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jlAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlAgregarMouseClicked
        // Evento click boton agregar
        AgregarEmpleado agregar = new AgregarEmpleado();
        
        agregar.setVisible(true);
        dispose();
    }//GEN-LAST:event_jlAgregarMouseClicked

    private void jlEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlEditarMouseClicked
        // evento clicl editar
        EditarEmpleado Editar = new EditarEmpleado();
        
        Editar.setVisible(true);
        dispose();
    }//GEN-LAST:event_jlEditarMouseClicked

    private void jlEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlEliminarMouseClicked
        // evento click eliminar
           EliminarEmpleado eliminar = new EliminarEmpleado();
        
        eliminar.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jlEliminarMouseClicked

    private void jlBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBuscarMouseClicked
        // evento click buscar
         BuscarEmpleado buscar = new BuscarEmpleado();
        
        buscar.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jlBuscarMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null,"¿Esta seguro que desea salir?", "Exit",dialog);

        if(result == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        this.setState(InicioAdmin.ICONIFIED);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        LogIn in = new LogIn();
      in.setVisible(true);
      dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        
       AddInsidencias inc = new AddInsidencias();
       
       inc.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ConsInc busInc = new ConsInc();
        busInc.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        DeleteIncidencias deleInc = new DeleteIncidencias();
        deleInc.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed
public void insesion(){
   
}
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        EditarInc EdiInc = new EditarInc();
        EdiInc.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:ç
         
    
    }//GEN-LAST:event_jButton3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel jlAgregar;
    private javax.swing.JLabel jlBuscar;
    private javax.swing.JLabel jlEditar;
    private javax.swing.JLabel jlEliminar;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lb4;
    private javax.swing.JLabel lbmenu;
    // End of variables declaration//GEN-END:variables
conection cc = new conection();
    Connection cn = (Connection) cc.getConnection();
}
